bot: nlu_dmp

configs:
    language: en-US
    health_check_interval: 750

policies:
  - name: custom_command_policy
    paths:    # Custom command tsv file paths
      - nlu_dmp_bot_custom_commands.tsv

  - name: nlu_data_match_policy
    paths:    # Paths to Nemo-formatted NLU training data
      - nlu_data/smalltalk

  - name: dialog_policy
    paths:
      - smalltalk/domain_smalltalk.yaml
      - ./default.yaml